### ISSUE TITLE
Escape sequences are visible in Raku error messages

### ISSUE THREAD

**Issue by error256** [codewars/raku-tap2codewars#5]
Escape sequences are visible in Raku error messages. For example:
https://www.codewars.com/kumite/5fdf5b523d98790018ddd861
Log:
`[31m===[0mSORRY![31m===[0m Error while compiling /workspace/./t/tests.t`
And it's shown as "Log", I think it should be STDERR? In a kumite without the tests it's in STDERR and there are no escape sequences.

**Comment by kazk** [comment]
When testing, STDERR is redirected to STDOUT because it's necessary to collect the failure information associated with the failed test case. The output is assumed to be a valid TAP.

This repository contains the code that processes TAP.

**Comment by error256** [comment]
It looks like color control sequences can be disabled setting an environment variable `RAKUDO_ERROR_COLOR=0`.
https://docs.raku.org/programs/03-environment-variables
https://www.codewars.com/kumite/604df4e21612ca001604b842

**Comment by kazk** [comment]
Thanks, I'll add it.

**Comment by kazk** [comment]
Deployed
